### ISSUE TITLE
Unable to install via Devmenu

### ISSUE THREAD

**Issue by IBM9100** [CVFireDragon/nspBuild#1]
I tried to convert Naruto (XCI) to NSP but could not install it in Devmenu

![a 2](https://user-images.githubusercontent.com/28668856/43141237-09e6d614-8f88-11e8-9526-cc430226d3ad.png)
![image](https://user-images.githubusercontent.com/28668856/43141609-e9b055c2-8f88-11e8-8e32-2616ca9f3c13.png)

**Comment by w1nn1ng** [comment]
Same error in both tinfoil and Devmenu as above trying to install Botw, Great concept hopefully there will be an easy fix. Was attempting XCI to NSP conversion. Compiled Via latest version of python 3.7

**Comment by IBM9100** [comment]
Maybe because it is CARD2?

**Comment by w1nn1ng** [comment]
Botw is card 1

**Comment by CVFireDragon** [comment]
you need sig patches (you need sx os) I think

**Comment by w1nn1ng** [comment]
I am running sx os v 1.4 (tried on v 1,3) and do have a paid version so it's not that.

**Comment by CVFireDragon** [comment]
hmm idk how to fix, I just wrote this simple code to put info in the nsp (maybe someone else can fix this)

**Comment by w1nn1ng** [comment]
Alright well thanks for getting us this far atleast! Now hopefully someone can take this farther. Only things odd I notice is the file is like 1 byte larger and if I don't add .nsp to the Filename when creating it is just created as a blank file and the switch doesn't even see it.

**Comment by CVFireDragon** [comment]
yeah you need to type .nsp

**Comment by CVFireDragon** [comment]
Ok, follow this guide to get your keys.txt: https://www.youtube.com/watch?v=de1OXyl15bI
then follow this guide after using your BIS keys to get your Registered folder using HacDiskMount: https://github.com/Adubbz/Tinfoil/tree/master/patches and add kip1=FS<FIRMWARE_VERSION>-exfat_nocmac_nosigchk.kip1 to hekate-ipl.ini.

**Comment by CVFireDragon** [comment]
So I'm reopening this real quick to state something. I just realized why the created NSP doesn't work. Because XCI's have a certain algorithm that I don't know how to decrypt. So, use NCA files @MooeKayo @w1nn1ng and it will work.
