### ISSUE TITLE
about your tool

### ISSUE THREAD

**Issue by ghost** [CVFireDragon/nspBuild#4]
it's not outdated
and tools like 4nxci is not a replacement for it
it's a good handy tool for building nsps (which are pfs0 containers without hash table)
i think you should update readme, remove outdated stuff, and clarify that this tool is just for packing ncas into nsp and it doesn't touch ncas (if they don't run, it's not tool's fault, just ncas don't pass switch checks or they are corrupted)

**Comment by CVFireDragon** [comment]
well, in that case, consider it done.
